"""create_initial_tables

Revision ID: 66254af2109a
Revises: 
Create Date: 2026-08-26 19:38:59.131119

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66254af2109a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clinical_constraints',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('medicine_name', sa.String(length=255), nullable=False),
    sa.Column('constraint_type', sa.String(length=100), nullable=False),
    sa.Column('constraint_rule', sa.Text(), nullable=False),
    sa.Column('severity', sa.String(length=50), nullable=False),
    sa.Column('evidence_source', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clinical_constraints_constraint_type'), 'clinical_constraints', ['constraint_type'], unique=False)
    op.create_index(op.f('ix_clinical_constraints_medicine_name'), 'clinical_constraints', ['medicine_name'], unique=False)
    op.create_table('medicine_alternatives',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_medicine', sa.String(length=255), nullable=False),
    sa.Column('alternative_medicine', sa.String(length=255), nullable=False),
    sa.Column('source_ingredient', sa.String(length=255), nullable=False),
    sa.Column('alternative_ingredient', sa.String(length=255), nullable=False),
    sa.Column('equivalence_type', sa.String(length=100), nullable=False),
    sa.Column('equivalence_evidence', sa.Text(), nullable=True),
    sa.Column('clinical_notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_medicine_alternatives_alternative_medicine'), 'medicine_alternatives', ['alternative_medicine'], unique=False)
    op.create_index(op.f('ix_medicine_alternatives_source_medicine'), 'medicine_alternatives', ['source_medicine'], unique=False)
    op.create_table('medicine_stock',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('medicine_name', sa.String(length=255), nullable=False),
    sa.Column('batch_code', sa.String(length=100), nullable=False),
    sa.Column('quantity_available', sa.Integer(), server_default='0', nullable=False),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('pharmacy_location', sa.String(length=255), nullable=True),
    sa.Column('is_available', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_medicine_stock_medicine_name'), 'medicine_stock', ['medicine_name'], unique=False)
    op.create_table('patients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_code', sa.String(length=50), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('sex', sa.String(length=20), nullable=False),
    sa.Column('weight_kg', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('pregnancy_status', sa.String(length=50), nullable=True),
    sa.Column('renal_status', sa.String(length=50), nullable=True),
    sa.Column('hepatic_status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patients_created_at'), 'patients', ['created_at'], unique=False)
    op.create_index(op.f('ix_patients_patient_code'), 'patients', ['patient_code'], unique=True)
    op.create_table('allergies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('allergen', sa.String(length=100), nullable=False),
    sa.Column('reaction', sa.String(length=255), nullable=True),
    sa.Column('severity', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_allergies_patient_id'), 'allergies', ['patient_id'], unique=False)
    op.create_table('prescriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('prescription_code', sa.String(length=50), nullable=False),
    sa.Column('prescriber_rule_code', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), server_default='active', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prescriptions_created_at'), 'prescriptions', ['created_at'], unique=False)
    op.create_index(op.f('ix_prescriptions_patient_id'), 'prescriptions', ['patient_id'], unique=False)
    op.create_index(op.f('ix_prescriptions_prescription_code'), 'prescriptions', ['prescription_code'], unique=True)
    op.create_table('prescription_medications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prescription_id', sa.Integer(), nullable=False),
    sa.Column('medicine_name', sa.String(length=255), nullable=False),
    sa.Column('active_ingredient', sa.String(length=255), nullable=False),
    sa.Column('strength', sa.String(length=100), nullable=False),
    sa.Column('dosage_form', sa.String(length=100), nullable=False),
    sa.Column('dose', sa.String(length=100), nullable=True),
    sa.Column('frequency', sa.String(length=100), nullable=True),
    sa.Column('duration_days', sa.Integer(), nullable=True),
    sa.Column('route', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['prescription_id'], ['prescriptions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prescription_medications_medicine_name'), 'prescription_medications', ['medicine_name'], unique=False)
    op.create_index(op.f('ix_prescription_medications_prescription_id'), 'prescription_medications', ['prescription_id'], unique=False)
    op.create_table('substitution_decisions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('prescription_medication_id', sa.Integer(), nullable=False),
    sa.Column('original_medicine', sa.String(length=255), nullable=False),
    sa.Column('recommended_medicine', sa.String(length=255), nullable=True),
    sa.Column('decision_status', sa.String(length=50), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('rule_evidence', sa.Text(), nullable=True),
    sa.Column('risk_level', sa.String(length=50), nullable=True),
    sa.Column('requires_human_confirmation', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('confidence_score', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['prescription_medication_id'], ['prescription_medications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_substitution_decisions_created_at'), 'substitution_decisions', ['created_at'], unique=False)
    op.create_index(op.f('ix_substitution_decisions_decision_status'), 'substitution_decisions', ['decision_status'], unique=False)
    op.create_index(op.f('ix_substitution_decisions_patient_id'), 'substitution_decisions', ['patient_id'], unique=False)
    op.create_index(op.f('ix_substitution_decisions_prescription_medication_id'), 'substitution_decisions', ['prescription_medication_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('decision_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('previous_status', sa.String(length=50), nullable=True),
    sa.Column('new_status', sa.String(length=50), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('actor_code', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['decision_id'], ['substitution_decisions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_decision_id'), 'audit_logs', ['decision_id'], unique=False)
    op.create_table('pharmacist_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('decision_id', sa.Integer(), nullable=False),
    sa.Column('review_status', sa.String(length=50), nullable=False),
    sa.Column('pharmacist_code', sa.String(length=50), nullable=True),
    sa.Column('override_reason', sa.Text(), nullable=True),
    sa.Column('review_notes', sa.Text(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['decision_id'], ['substitution_decisions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pharmacist_reviews_decision_id'), 'pharmacist_reviews', ['decision_id'], unique=False)
    op.create_index(op.f('ix_pharmacist_reviews_review_status'), 'pharmacist_reviews', ['review_status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pharmacist_reviews_review_status'), table_name='pharmacist_reviews')
    op.drop_index(op.f('ix_pharmacist_reviews_decision_id'), table_name='pharmacist_reviews')
    op.drop_table('pharmacist_reviews')
    op.drop_index(op.f('ix_audit_logs_decision_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_substitution_decisions_prescription_medication_id'), table_name='substitution_decisions')
    op.drop_index(op.f('ix_substitution_decisions_patient_id'), table_name='substitution_decisions')
    op.drop_index(op.f('ix_substitution_decisions_decision_status'), table_name='substitution_decisions')
    op.drop_index(op.f('ix_substitution_decisions_created_at'), table_name='substitution_decisions')
    op.drop_table('substitution_decisions')
    op.drop_index(op.f('ix_prescription_medications_prescription_id'), table_name='prescription_medications')
    op.drop_index(op.f('ix_prescription_medications_medicine_name'), table_name='prescription_medications')
    op.drop_table('prescription_medications')
    op.drop_index(op.f('ix_prescriptions_prescription_code'), table_name='prescriptions')
    op.drop_index(op.f('ix_prescriptions_patient_id'), table_name='prescriptions')
    op.drop_index(op.f('ix_prescriptions_created_at'), table_name='prescriptions')
    op.drop_table('prescriptions')
    op.drop_index(op.f('ix_allergies_patient_id'), table_name='allergies')
    op.drop_table('allergies')
    op.drop_index(op.f('ix_patients_patient_code'), table_name='patients')
    op.drop_index(op.f('ix_patients_created_at'), table_name='patients')
    op.drop_table('patients')
    op.drop_index(op.f('ix_medicine_stock_medicine_name'), table_name='medicine_stock')
    op.drop_table('medicine_stock')
    op.drop_index(op.f('ix_medicine_alternatives_source_medicine'), table_name='medicine_alternatives')
    op.drop_index(op.f('ix_medicine_alternatives_alternative_medicine'), table_name='medicine_alternatives')
    op.drop_table('medicine_alternatives')
    op.drop_index(op.f('ix_clinical_constraints_medicine_name'), table_name='clinical_constraints')
    op.drop_index(op.f('ix_clinical_constraints_constraint_type'), table_name='clinical_constraints')
    op.drop_table('clinical_constraints')
    # ### end Alembic commands ###
